# Generated by Django 6.0.7 on 2026-07-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula_foto',
            field=models.FileField(blank=True, null=True, upload_to='cedula/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='notas',
            field=models.FileField(blank=True, null=True, upload_to='notas/'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='titulo',
            field=models.FileField(blank=True, null=True, upload_to='titulo/'),
        ),
    ]
